name: Docs Deployment
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  dumi-build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run docs:build
      - run: npm run docs:deploy
