name: dumi-build-docs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  dumi-build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run docs:build
      - name: deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "dumi-build-docs stillba@icloud.com"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
